language: java
jdk: openjdk11

# docker, see: https://docs.travis-ci.com/user/reference/overview/
sudo: false
dist: trusty

addons:
  firefox: latest
  chrome: stable

install: true # disable default mvn install

notifications:
  slack:
    secure: CBl3zx9fyajOXqflYsPMUy0I1pU/6LiLs19UJ6If+YMRWP8kUV35/lrEzbn4zAmdar7FnDkLPXGVMcwNgOQazHTC9jXft0aQIojB4TIT2l+Cn65r0UfKHGexwheO48kbDKTZApkExKUAulDPSaqqfB+ysA8RU4gzHdXnf9Ee1Xx9I0niDHSaDCI3g0ZfjMX2F7f81f7gLB2eWgoj9a9w6/ZX2EcDj433i7QRaZqC2xfyzl/rtot4AiM/7q7FEfwW5JvFQh3iQ3d4L5vGoWXtRLA9qs1K82jbPRHjDPIx6JHUe8tL7r7Idfne7hIqKM9olAFF6YshUKLBU2DhGA3rTYo/pTC0h5e6Dok78NWU+zP9elTZ7UhryI8jxamSBBVHvuVM0Ahcgx5lfbIzCZGfKL4SbR3KyiXMcq3MkS10nbbiFHC3uHB8RWZVHqZccZ5r5+W/WjVAHLrNd61YtdlpkqcGNY66Mw38tlOhpYpKInxamEy2k0bmHgI00mL2GNHy5ChnobuinwRk4dqyDprDPmielmjyHOGizbCLH7zJEpm2tVaXMneq+iIJogJgrK9Mq/noHSABLNoq794G9Rnlh1C/PdbS2E25/zgCspJw+OM0Ne1WAScXum2dVLh5hBFRm0LCi54U2ERKLJgts9PMdyXqU9Q4SX9ad31sg+b+as4=

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - CAPTURE_URL="http://capture-6c06138r.cloudapp.net"
    - SUT_NAME="frameworkium-examples"
    - SUT_VERSION=${TRAVIS_BRANCH}
    - THREAD_COUNT=2
    - SELENIUM_MAJ_VER=3.141
    - SELENIUM_VER=${SELENIUM_MAJ_VER}.59
    - SELENIUM_JAR=selenium-server-standalone-${SELENIUM_VER}.jar
    - GECKO_VER=0.24.0
    - CHROME_DRIVER_VER=77.0.3865.40
    # override Travis default to give browsers more room
    - _JAVA_OPTIONS="-Xmx1024m -Xms128m"
    # Required to turn on workaround for the following issue:
    # https://github.com/travis-ci/travis-ci/issues/8836
    - CHROME_NO_SANDBOX=true

before_script:
  # Set up Selenium Grid Hub
  - wget --quiet https://selenium-release.storage.googleapis.com/${SELENIUM_MAJ_VER}/${SELENIUM_JAR}
  - java -Xmx128m -jar ${SELENIUM_JAR} -role hub > /dev/null 2>&1 &

  # Download geckodriver
  - wget --quiet https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VER}/geckodriver-v${GECKO_VER}-linux64.tar.gz
  - tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz

  # Download chromedriver
  - wget --quiet https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VER}/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip

  # Wait for grid hub to be up
  - until $(curl --output /dev/null --silent --fail http://localhost:4444/grid/console); do printf '.'; sleep 1; done

  # Setup Firefox Selenium Grid Node
  - java -Xmx128m -jar ${SELENIUM_JAR} -role node -hub http://localhost:4444/grid/register -browser browserName=firefox,maxInstances=${THREAD_COUNT} -maxSession ${THREAD_COUNT} -port 5555 > /dev/null 2>&1 &

  # Set up Chrome Selenium Grid Node
  - java -Xmx128m -jar ${SELENIUM_JAR} -role node -hub http://localhost:4444/grid/register -browser browserName=chrome,maxInstances=${THREAD_COUNT} -maxSession ${THREAD_COUNT} -port 5556 > /dev/null 2>&1 &

script:
  # Download deps, compile and run checkstyle
  - mvn test-compile -B --show-version -Dmaven.javadoc.skip=true

  # Firefox on the grid
  - mvn verify -B -Dthreads=1 -Dconfig=FirefoxGrid.yaml -DreuseBrowser=true -Dheadless=true -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # Add offline option (-o) to prevent timeouts fetching snapshot info again
  # Firefox off the grid
  - mvn verify -B -o -Dthreads=1 -Dbrowser=firefox -DreuseBrowser=true -Dheadless=true -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}" 2> /dev/null

  # Chrome on the grid
  - mvn verify -B -o -Dthreads=${THREAD_COUNT} -Dbrowser=chrome -DreuseBrowser=true -Dheadless=true -DgridURL=http://localhost:4444/wd/hub -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # Query Jira for which test to run and then log results to Jira
  # Disabled until we have a JIRA to use
  # - mvn verify -B -Dbrowser=chrome -Dheadless=true -DgridURL=http://localhost:4444/wd/hub -DjiraURL="http://52.29.130.45:8080" -DjqlQuery="issueKey=TEST-1" -DresultVersion="BUILD TEST VERSION" -DzapiCycleRegex="Test Cycle" -DjiraUsername=frameworkium -DjiraPassword=frameworkium -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # SauceLabs- disabled until we have a sauce account to use
  # - mvn verify -Dsauce=true -Dplatform=ios -Dbrowser=safari -DplatformVersion=8.0 -Ddevice=iPad -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # Allure report
  - mvn allure:report -B
